### ISSUE TITLE
Track name too long

### ISSUE THREAD

**Issue by kaiartikkas** [andremichelle/audiotool-hoover#1]
Sometimes tracks have weird names like [zalgo](https://www.zalgo.org/) text. It would be best to limit track names or skip these tracks, and provide a manual download link at the end or something.
![image](https://github.com/andremichelle/audiotool-hoover/assets/52412391/e9939101-d60b-46cc-a107-0607b80a52f2)

**Comment by andremichelle** [comment]
Restricted file names to 32 chars.
